root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
env:
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
