name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: lint
        run: pnpm run lint:ci
      - name: build check
        run: pnpm build
      - name: test
        run: pnpm test
      - uses: codecov/codecov-action@v4.6.0
